spring:
  datasource:
    url: jdbc:mysql://192.168.60.132:3306/shm?useUnicode=true&characterEncoding=UTF-8
    username: demo
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  ftp:
    host: "127.0.0.1"
    port: 6868
    username: "shm"
    password: "vupt172Fuzzy96"
    DepartmentSwitchReportsFolder: "DepartmentSwitchReports"
