config:
  app:
    info: "PHẦN MỀM QUẢN LÝ TRANG THIẾT BỊ PHẦN CỨNG SHM
        \nTác giả : Phạm Tuấn Vũ
        \nĐịa điểm : Bệnh viện Đa khoa khu vực Long Thành
        \nEmail: vu.pt172@gmail.com
        \nPhiên bản: 2.0.2"
    update: "Cập nhật:
                \n -  "

spring:
  profiles:
    active: lan

