package com.vupt.SHM.constant;

public enum AuthorityCode {
    ROLE_ADMIN("ROLE_ADMIN"),
    ROLE_MANAGER("ROLE_MANAGER"),
    ROLE_VIEWER("ROLE_VIEWER"),

    VIEW_ACCOUNT("VIEW_ACCOUNT"),
    CREATE_ACCOUNT("CREATE_ACCOUNT"),
    UPDATE_ACCOUNT("UPDATE_ACCOUNT"),
    DELETE_ACCOUNT("DELETE_ACCOUNT"),
    FIND_ACCOUNT("FIND_ACCOUNT"),

    VIEW_EMPLOYEE("VIEW_EMPLOYEE"),
    CREATE_EMPLOYEE("CREATE_EMPLOYEE"),
    UPDATE_EMPLOYEE("UPDATE_EMPLOYEE"),
    DELETE_EMPLOYEE("DELETE_EMPLOYEE"),
    FIND_EMPLOYEE("FIND_EMPLOYEE"),

    VIEW_DEPARTMENT("VIEW_DEPARTMENT"),
    CREATE_DEPARTMENT("CREATE_DEPARTMENT"),
    UPDATE_DEPARTMENT("UPDATE_DEPARTMENT"),
    DELETE_DEPARTMENT("DELETE_DEPARTMENT"),
    FIND_DEPARTMENT("FIND_DEPARTMENT"),

    VIEW_CATEGORY("VIEW_CATEGORY"),
    CREATE_CATEGORY("CREATE_CATEGORY"),
    UPDATE_CATEGORY("UPDATE_CATEGORY"),
    DELETE_CATEGORY("DELETE_CATEGORY"),
    FIND_CATEGORY("FIND_CATEGORY"),

    VIEW_EQUIPMENT("VIEW_EQUIPMENT"),
    CREATE_EQUIPMENT("CREATE_EQUIPMENT"),
    UPDATE_EQUIPMENT("UPDATE_EQUIPMENT"),
    DELETE_EQUIPMENT("DELETE_EQUIPMENT"),
    FIND_EQUIPMENT("FIND_EQUIPMENT"),

    VIEW_SWITCH_DEPARTMENT("VIEW_SWITCH_DEPARTMENT"),
    CREATE_SWITCH_DEPARTMENT("CREATE_SWITCH_DEPARTMENT"),
    VIEW_DEPARTMENT_SWITCH("VIEW_DEPARTMENT_SWITCH"),
    FIND_DEPARTMENT_SWITCH("FIND_DEPARTMENT_SWITCH"),
    CREATE_DEPARTMENT_SWITCH("CREATE_DEPARTMENT_SWITCH"),
    UPDATE_DEPARTMENT_SWITCH("UPDATE_DEPARTMENT_SWITCH"),
    DELETE_DEPARTMENT_SWITCH("DELETE_DEPARTMENT_SWITCH"),

    VIEW_EQUIPMENT_HISTORY("VIEW_EQUIPMENT_HISTORY"),
    FIND_EQUIPMENT_HISTORY("FIND_EQUIPMENT_HISTORY"),

    VIEW_REPORT_SYSTEM("VIEW_REPORT_SYSTEM"),
    VIEW_STATISTIC("VIEW_STATISTIC");
    private String authority;

    AuthorityCode(String authority) {
        this.authority = authority;
    }

    public String getAuthority() {
        return this.authority;
    }

    public void setAuthority(String authority) {
        this.authority = authority;
    }
}

